2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Configure stats pid to 89997
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Loading settings from /Users/zhifu/.config/wandb/settings
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Loading settings from /Users/zhifu/funasr1.0/wandb/settings
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-25 21:14:46,147 WARNING MainThread:89997 [wandb_setup.py:_flush():76] Could not find program at <input>
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '<input>'}
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_init.py:_log_setup():521] Logging user logs to ./wandb/run-20240425_211446-lkqptn01/logs/debug.log
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_init.py:_log_setup():522] Logging internal logs to ./wandb/run-20240425_211446-lkqptn01/logs/debug-internal.log
2024-04-25 21:14:46,147 INFO    MainThread:89997 [wandb_init.py:init():561] calling init triggers
2024-04-25 21:14:46,148 INFO    MainThread:89997 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'a': 1}
2024-04-25 21:14:46,148 INFO    MainThread:89997 [wandb_init.py:init():611] starting backend
2024-04-25 21:14:46,148 INFO    MainThread:89997 [wandb_init.py:init():615] setting up manager
2024-04-25 21:14:46,153 INFO    MainThread:89997 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-25 21:14:46,156 INFO    MainThread:89997 [wandb_init.py:init():623] backend started and connected
2024-04-25 21:14:46,171 INFO    MainThread:89997 [wandb_init.py:init():715] updated telemetry
2024-04-25 21:14:46,282 INFO    MainThread:89997 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-25 21:14:46,836 ERROR   MainThread:89997 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-04-25 21:14:48,147 ERROR   MainThread:89997 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/Users/zhifu/miniconda3/envs/funasr/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/Users/zhifu/miniconda3/envs/funasr/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
